import pygame
import sys
import math
from numba import jit

RESOLUTION = WIDTH,HEIGHT = 1000,500
FRAMESPERSECOND = 120

PLAYERPOSITION = 1.5,5
PLAYERANGLE = 0
PLAYERSPEED = 0.009
PLAYERROTATIONSPEED = 0.009
PLAYERMAXSIZE = 60

FIELDOFVIEW = math.pi / 3.5
NUMBEROFRAYS = WIDTH // 2
DELTAANGLE = FIELDOFVIEW / NUMBEROFRAYS
MAXDEPTH = 20

DISTANCE3D = (WIDTH / 2) / math.tan((FIELDOFVIEW/2))
SCREENSCALE = WIDTH // NUMBEROFRAYS
TEXTURESIZE = 256

MOUSESENSITIVITY = 0.0003
MOUSEMAX = 40
MOUSEBORDERLEFT = 100
MOUSEBORDERIGHT = WIDTH - MOUSEBORDERLEFT